# HOSTING PLATFORM RULE - not editable by customers or support.
location = /wp-admin/admin-ajax.php {
    limit_req zone=ajax burst=10 nodelay;
    include fastcgi_params;
    fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
    fastcgi_param HTTPS $lab_https;
    fastcgi_param HTTP_HOST $lab_host;
    fastcgi_pass wordpress:9000;
}
